apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
      - args:
        - ./wait-for-it.sh
        - hbase:2181
        - -t
        - "300"
        - --
        - make
        - runjar
        env:
        - name: VCAP_APPLICATION
        - name: VCAP_SERVICES
        image: backend
        name: backend
        ports:
        - containerPort: 8080
        resources: {}
        workingDir: /app
      restartPolicy: Always
status: {}
