apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: gearpump
  name: gearpump
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gearpump
    spec:
      containers:
      - image: gearpump
        name: gearpump
        ports:
        - containerPort: 8090
        resources: {}
      restartPolicy: Always
status: {}
