apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: hbase
  name: hbase
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: hbase
    spec:
      containers:
      - image: dajobe/hbase
        name: hbase
        ports:
        - containerPort: 2181
        - containerPort: 9090
        - containerPort: 60000
        - containerPort: 60020
        resources: {}
      restartPolicy: Always
status: {}
