apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: rules-engine-build
  name: rules-engine-build
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rules-engine-build
    spec:
      containers:
      - args:
        - ./wait-for-it.sh
        - gearpump:8090
        - -t
        - "300"
        - --
        - ./wait-for-it.sh
        - nginx:80
        - -t
        - "300"
        - --
        - ./local-push-to-gearpump.sh
        env:
        - name: VCAP_APPLICATION
        - name: VCAP_SERVICES
        image: rules-engine-build
        name: rules-engine-build
        resources: {}
        workingDir: /app
      restartPolicy: Always
status: {}
