apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: websocket-server
  name: websocket-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: websocket-server
    spec:
      containers:
      - args:
        - ./wait-for-it.sh
        - postgres:5432
        - -t
        - "300"
        - --
        - ./scripts/docker-start.sh
        env:
        - name: NODE_ENV
          value: local
        - name: TEST
        - name: VCAP_APPLICATION
        - name: VCAP_SERVICES
        image: websocket-server
        name: websocket-server
        ports:
        - containerPort: 5000
        resources: {}
        workingDir: /app
      restartPolicy: Always
status: {}
